### ISSUE TITLE
Mediafile error

### ISSUE THREAD

**Issue by kernitus** [tweitzel/beets-recordingdate#5]
Having the most up-to-date version of beets and the recordingdate plugin, I get an error when running:

```
Traceback (most recent call last):
	File ".local/bin/beet", line 33, in <module>
	sys.exit(load_entry_point('beets==1.4.9', 'console_scripts', 'beet')())
	File ".local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
	_raw_main(args)
	File ".local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
	subcommands, plugins, lib = _setup(options, lib)
	File ".local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1135, in _setup
	plugins = _load_plugins(config)
	File ".local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1121, in _load_plugins
	plugins.send("pluginload")
	File ".local/lib/python3.8/site-packages/beets/plugins.py", line 488, in send
	for handler in event_handlers()[event]:
	File ".local/lib/python3.8/site-packages/beets/plugins.py", line 471, in event_handlers
	for plugin in find_plugins():
	File ".local/lib/python3.8/site-packages/beets/plugins.py", line 307, in find_plugins
	_instances[cls] = cls()
	File "/usr/lib/python3.8/site-packages/beets_recordingdate-0.3-py3.8.egg/beetsplug/recordingdate.py", line 39, in __init__
	self.add_media_field(recording_field, field)
	File ".local/lib/python3.8/site-packages/beets/plugins.py", line 209, in add_media_field
	mediafile.MediaFile.add_field(name, descriptor)
	File ".local/lib/python3.8/site-packages/beets/mediafile.py", line 1578, in add_field
	raise ValueError(
			ValueError: <mediafile.MediaField object at 0x7f346d45a220> must be an instance of MediaField
```

If I revert commit c385b50 and reinstall, then the plugin start working. Is this something wrong with my setup, or did something change in the MediaField module?

**Comment by tweitzel** [comment]
What version of beets and mediafile are you running? Beets split out the mediafile module into its own thing some time ago, and the commit in question removes deprecated calls to the embedded mediafile module in favor of an external one.

Try installing mediafile using pip3 or whatever python package manager you're using.

**Comment by kernitus** [comment]
I am using beets version 1.4.9 and mediafile version 0.5.0, both acquired using pip.

**Comment by jimcampbell100** [comment]
Hi - I'm getting nearly the exact same error.  I have beets 1.4.9 and mediafile 0.6.0, installed via pip.

Anything I can do to debug?  Thanks!

```
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1135, in _setup
    plugins = _load_plugins(config)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1121, in _load_plugins
    plugins.send("pluginload")
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 488, in send
    for handler in event_handlers()[event]:
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 471, in event_handlers
    for plugin in find_plugins():
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 307, in find_plugins
    _instances[cls] = cls()
  File "/usr/lib/python3.8/site-packages/beets_recordingdate-0.3-py3.8.egg/beetsplug/recordingdate.py", line 39, in __init__
    self.add_media_field(recording_field, field)
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 209, in add_media_field
    mediafile.MediaFile.add_field(name, descriptor)
  File "/usr/lib/python3.8/site-packages/beets/mediafile.py", line 1578, in add_field
    raise ValueError(
ValueError: <mediafile.MediaField object at 0x7f9a79b69550> must be an instance of MediaField
```

**Comment by kernitus** [comment]
> Hi - I'm getting nearly the exact same error. I have beets 1.4.9 and mediafile 0.6.0, installed via pip.
> 
> Anything I can do to debug? Thanks!
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/beet", line 11, in <module>
>     load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
>   File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
>     _raw_main(args)
>   File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
>     subcommands, plugins, lib = _setup(options, lib)
>   File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1135, in _setup
>     plugins = _load_plugins(config)
>   File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1121, in _load_plugins
>     plugins.send("pluginload")
>   File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 488, in send
>     for handler in event_handlers()[event]:
>   File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 471, in event_handlers
>     for plugin in find_plugins():
>   File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 307, in find_plugins
>     _instances[cls] = cls()
>   File "/usr/lib/python3.8/site-packages/beets_recordingdate-0.3-py3.8.egg/beetsplug/recordingdate.py", line 39, in __init__
>     self.add_media_field(recording_field, field)
>   File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 209, in add_media_field
>     mediafile.MediaFile.add_field(name, descriptor)
>   File "/usr/lib/python3.8/site-packages/beets/mediafile.py", line 1578, in add_field
>     raise ValueError(
> ValueError: <mediafile.MediaField object at 0x7f9a79b69550> must be an instance of MediaField
> ```

I don't really remember what changed but I stopped getting that error. I seem to recall having to install beets 1.5.0 by directly cloning the repository or using the [AUR git](https://aur.archlinux.org/packages/beets-git/) package. Either way, I basically completely rewrote this plugin on [my own fork](https://github.com/kernitus/beets-oldestdate) because it straight up didn't do its job properly, due to the way most recordings on musicbrainz lack the relations attributes that this plugin relied on. I instead made it work its way around using the work attribute, which is present on most recordings, and only needing minimal manual intervention.

**Comment by tweitzel** [comment]
The basic thing is this: I started hacking at the plugin to make it work with 1.5.0, which changes the way MediaFile is called, then musicbrainz changed things (for the better!) and added the Work relationship. Since @kernitus rewrote the plugin anyway, I consider their version to be better and use that. I'll probably be editing my readme.md to point people towards their fork.
